/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echoServer;

import org.junit.Test;
import static org.junit.Assert.*;

public class echoServerTest {
    @Test public void testAppHasAGreeting() {
        echoServer classUnderTest = new echoServer();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
